### ISSUE TITLE
socket functions are not wrapped as intended

### ISSUE THREAD

**Issue by ChrisYo-o** [heroiclabs/nakama-defold#82] opened 2024-09-25 14:22 UTC
According to the official Nakama docs here:
https://heroiclabs.com/docs/nakama/concepts/chat/

This code should return a table with id as a child

```
local roomname = "MarvelMovieFans"
local persistence = true
local hidden = false

local channel = socket.channel_join(roomname, socket.CHANNELTYPE_ROOM, persistence, hidden)

print("Now connected to channel id: " .. channel.id);
```

The way it currently works in defold is that a table containing a channel table is returned, so in defold we would have to use
`channel.channel.id` to get the correct channel id.

Also, for some reason I cannot understand, the channel_id is a very unintuitive name like `1...MarvelMovieFans` or `2...MarvelMovieFans` instead of `MarvelMovieFans`. I'm not sure if the defold wrapper is the one messing up the channel_id and requires the weird name to be used, or if nakama is bugged - but I suspect it's the nakama-defold implementation.

The nakama-defold documentation is also wrong because of this:

```
-- send channel join message
local channel_id = "pineapple-pizza-lovers-room"
local result = socket.channel_join(socket, 1, channel_id, false, false)

-- send channel messages
local result = socket.channel_message_send(channel_id, "Pineapple doesn't belong on a pizza!")
```

It's my understanding that this WOULD work if we could actually use the `channel_id` as the nakama docs intend for us to (no weird `2..` prefix), so if that's fixed this documentation may be automatically fixed - that's the ideal situation.

**Comment by ChrisYo-o** [comment] 2024-09-25 14:26
Here is a pretty printed result of `pprint`ing what `socket.channel_join` returns using `MarvelMovieFans` as `roomname`
![image](https://github.com/user-attachments/assets/3a9a3d55-dad4-420a-94fe-2a987912a78b)

**Comment by britzl** [comment] 2024-10-17 09:35
> This code should return a table with id as a child
> 
> ```
> local roomname = "MarvelMovieFans"
> local persistence = true
> local hidden = false
> 
> local channel = socket.channel_join(roomname, socket.CHANNELTYPE_ROOM, persistence, hidden)
> 
> print("Now connected to channel id: " .. channel.id);
> ```
>
> The way it currently works in defold is that a table containing a channel table is returned, so in defold we would have to use channel.channel.id to get the correct channel id.

The official documentation on the other hand shows something else:

https://heroiclabs.com/docs/nakama/concepts/chat/#rooms

```lua
local roomname = "MarvelMovieFans"
local persistence = true
local hidden = false

local result = socket.channel_join(roomname, socket.CHANNELTYPE_ROOM, persistence, hidden)

print("Now connected to channel id: " .. result.channel.id)
```

As you can see above, the socket.channel_join() will return a result "object" (Lua table). The result object will either return the requested data `result.channel` or error information.

> Also, for some reason I cannot understand, the channel_id is a very unintuitive name like `1...MarvelMovieFans` or `2...MarvelMovieFans` instead of `MarvelMovieFans`. I'm not sure if the defold wrapper is the one messing up the channel_id and requires the weird name to be used, or if nakama is bugged - but I suspect it's the nakama-defold implementation.

I will look into this though. Seems strange.

**Comment by britzl** [comment] 2024-10-17 11:17
> I will look into this though. Seems strange.

I'm looking into this right now. The json serialized data (https://github.com/heroiclabs/nakama-defold/blob/master/nakama/engine/defold.lua#L203) looks like this:

```json
{"channel_join":{"type":1,"hidden":false,"target":"pineapple-pizza-lovers-room","persistence":false},"cid":"1"}
```

There is no modification of the data before it is sent at least... 🤔 

And if I look at what is received from the websocket (https://github.com/heroiclabs/nakama-defold/blob/master/nakama/engine/defold.lua#L190):

```
EVENT_MESSAGE: 	{"cid":"1","channel":{"id":"2...pineapple-pizza-lovers-room","self":{"user_id":"91a85365-6f79-4577-9f41-10b197883b6f","session_id":"a18ea694-8c76-11ef-992e-7106fdcb5b46","username":"britzl"},"room_name":"pineapple-pizza-lovers-room"}}
```

It is possible to get [additional logging from the websocket](https://github.com/defold/extension-websocket/?tab=readme-ov-file#debugging) layer by adding the following to game.project using a text editor:

```
[websocket]
debug = 2
```

With this enabled you see:

```
WARNING:WEBSOCKET: Sent buffer: '\81\ef%x\d66' 6 bytes
WARNING:WEBSOCKET: Sent buffer: '^Z\b5_AZ\ec\14\14Z\fa\14F\10\b7XK\1d\baiO\17\bfX\07B\ad\14Q\19\a4Q@\0c\f4\0c\07\08\bfX@\19\a6FI\1d\fbFL\02\acW\08\14\b9@@\n\a5\1bW\17\b9[\07T\f4B\\08\b3\14\1fI\fa\14U\1d\a4EL\0b\a2SK\1b\b3\14\1f\1e\b7ZV\1d\fa\14M\11\b2R@\16\f4\0cC\19\baE@\05\ab' 111 bytes
WARNING:WEBSOCKET: Received bytes: '\81~\00\ea{"cid":"1","channel":{"id":"2...pineapple-pizza-lovers-room","self":{"user_id":"91a85365-6f79-4577-9f41-10b197883b6f","session_id":"69baab80-8c77-11ef-992e-7106fdcb5b46","username":"britzl"},"room_name":"pineapple-pizza-lovers-room"}}\81~\00\fa{"channel_presence_event":{"channel_id":"2...pineapple-pizza-lovers-room","joins":[{"user_id":"91a85365-6f79-4577-9f41-10b197883b6f","session_id":"69baab80-8c77-11ef-992e-7106fdcb5b46","username":"britzl"}],"room_name":"pineapple-pizza-lovers-room"}}' 492 bytes
WARNING:WEBSOCKET: PushMessage '{"cid":"1","channel":{"id":"2...pineapple-pizza-lovers-room","self":{"user_id":"91a85365-6f79-4577-9f41-10b197883b6f","session_id":"69baab80-8c77-11ef-992e-7106fdcb5b46","username":"britzl"},"room_name":"pineapple-pizza-lovers-room"}}' 234 bytes
WARNING:WEBSOCKET: PushMessage '{"channel_presence_event":{"channel_id":"2...pineapple-pizza-lovers-room","joins":[{"user_id":"91a85365-6f79-4577-9f41-10b197883b6f","session_id":"69baab80-8c77-11ef-992e-7106fdcb5b46","username":"britzl"}],"room_name":"pineapple-pizza-lovers-room"}}' 250 bytes
```

Note that the `room_name` is `pineapple-pizza-lovers-room`. It is the chat channel which has a different name (`2...pineapple-pizza-lovers-room`).

This brings me to your statement:

> the way the `channel.id` is generated needs to be investigated as it seems to be incorrect, it should be the same as room_name in this case.

Can you point to documentation to back this up? Actually, I looked at the server code and then channel id is composed of a number of different components:

https://github.com/heroiclabs/nakama/blob/master/server/core_channel.go#L588

```ts
return fmt.Sprintf("%v.%v.%v.%v", stream.Mode, subject, subcontext, stream.Label), nil
```

`stream.Mode` for channel is 2. There is no `subject` and no `subcontext`, and `stream.Label` is `pineapple-pizza-lovers-room` which will result in "2...pineapple-pizza-lovers-room".

Everything is working as intended. I'm closing this.

**Closed by britzl** 2024-10-17 11:17 UTC
